field: 7171b81e-8b3c-4b8d-8c47-b13f0504a2f6
fieldLayouts:
  2c4563c8-28b4-44c5-a7dd-b683aa45793c:
    tabs:
      -
        elements:
          -
            fieldUid: 5844d6ad-ddce-41f9-8b36-7c081ef3fd41
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5844d6ad-ddce-41f9-8b36-7c081ef3fd41:
    contentColumnType: text
    fieldGroup: null
    handle: tipContent
    instructions: ''
    name: 'Tip Content'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeTip
name: 'Recipe Tip'
sortOrder: 2
