field: 7171b81e-8b3c-4b8d-8c47-b13f0504a2f6
fieldLayouts:
  51fa4c6d-3a3e-4ddf-9f0b-3271c7910042:
    tabs:
      -
        elements:
          -
            fieldUid: bbe11bf6-409b-4673-ae96-1aa1617613d3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 52dc7f30-fd86-4524-a1b2-251c5954c2e2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  52dc7f30-fd86-4524-a1b2-251c5954c2e2:
    contentColumnType: text
    fieldGroup: null
    handle: stepsContent
    instructions: ''
    name: 'Steps Content'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Step Instructions'
                -
                  - handle
                  - stepInstructions
                -
                  - width
                  - ''
                -
                  - type
                  - multiline
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  bbe11bf6-409b-4673-ae96-1aa1617613d3:
    contentColumnType: text
    fieldGroup: null
    handle: stepsTitle
    instructions: ''
    name: 'Steps Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeSteps
name: 'Recipe Steps'
sortOrder: 4
