fieldLayouts:
  b9b6b267-f8ef-4785-9b12-bf7de91df4aa:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: 'Drink Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 9d5cebbb-c698-4141-8318-c824f48bd2c5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 033e4396-fbe5-4e48-b2e3-865475cd4910
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eab28bdf-3d8a-44bc-834b-7391e4b08520
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1bd27780-77ff-4095-b2f2-fc35406d1197
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4b4dd321-3234-46c1-865a-ff8b646190d1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Drink Details'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: fbc7bb15-eb40-4f5d-bee0-76bfac0e290f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Drink Index'
        sortOrder: 2
handle: drinks
hasTitleField: true
name: Drinks
section: 45e355d7-ce5f-4071-a6e3-9ba4f908bc71
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
