fieldLayouts:
  f1002ed2-df92-4743-9195-69936cc3c9a0:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 0ba189cb-89f8-4ed3-b057-9b36c99def51
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: drinkStyles
name: 'Drink Styles'
siteSettings:
  3f87edb4-b597-474f-aa87-a4261e199acf:
    hasUrls: true
    template: styles/_entry
    uriFormat: 'styles/{slug}'
structure:
  maxLevels: null
  uid: 5055ff7d-9a81-4766-b1d4-19afef55473c
