contentColumnType: text
fieldGroup: 2a7b18dc-2086-41d0-b181-47598dc54e7b
handle: aboutCatchphrase
instructions: ''
name: 'About Catchphrase'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
