contentColumnType: string
fieldGroup: a38951ff-c2b7-4d4d-9fca-71104ac46ba5
handle: drinkImage
instructions: ''
name: 'Drink Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:1fabe0c9-3e5d-4c5f-98ab-44648dce2e2c'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add a drink image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1fabe0c9-3e5d-4c5f-98ab-44648dce2e2c'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:1fabe0c9-3e5d-4c5f-98ab-44648dce2e2c'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
